### ISSUE TITLE
Error load crypto.js

### ISSUE THREAD

**Issue by Gxerxes** [born2net/ng2Boilerplate#14]
Error: Error: XHR error (404 Not Found) loading http://localhost:8080/crypto.js(…) "error system.js Error: Error: XHR error (404 Not Found) loading http://localhost:8080/crypto.js
	Error loading http://localhost:8080/crypto.js as "crypto" from http://localhost:8080/jspm_packages/npm/reflect-metadata@0.1.3/Reflect.js"

**Comment by ojhughes** [comment]
I am having the same issue here

**Comment by Cabarfeidh** [comment]
...and here!

**Comment by born2net** [comment]
I will awaiting for .13 ng2 should come today and re-test and report back
regards

**Comment by ishara** [comment]
Me tooo.

**Comment by born2net** [comment]
fixed in today's update to beta 0.14
