### ISSUE TITLE
Duplicate modules in node_modules and jspm_modules

### ISSUE THREAD

**Issue by netlander** [born2net/ng2Boilerplate#15]
After doing `npm install` and `gulp development` I get some missing libraries so I `npm i` again, that's when jspm kicks in and downloads the entire web to my disk. Is it meant to do that?

Being new to jspm I hoped that it wouldn't replicate the modules that are already in `node_modules` what is going on? Am I missing something?

**Comment by born2net** [comment]
npm is just for dev mode so ts is happy... until ts 2.0 is out and supports module mapping, at which point node_modules will go away completely and only jspm used... hope this clears things up
