### ISSUE TITLE
Create a `Skeleton` branch.

### ISSUE THREAD

**Issue by jakeNiemiec** [born2net/ng2Boilerplate#18]
Idea taken from a [proprietary, **pay to access**, AngularJS template repo](https://github.com/withinpixels/fuse/blob/skeleton/README.md) ([more info here](http://themeforest.net/item/fuse-angularjs-material-design-admin-template/12931855)). They have a branch called `Skeleton` which includes everything from master branch except the demo content. "Ideal for quickly start creating your app without worrying about cleaning up the demos.". This could be very useful for this project to have.

**Comment by born2net** [comment]
broken link

**Comment by jakeNiemiec** [comment]
Forgot that its private. [This is the page for it](http://themeforest.net/item/fuse-angularjs-material-design-admin-template/12931855). 

I mainly wanted to discuss the idea of having a `skeleton` branch for ng2Boilerplate that includes all the tooling but is easy to adapt for your own content. A blank canvass.

**Comment by born2net** [comment]
sure you are welcome to use it as you wish... MIT license ;)
and I do recommend including redux in that blank core
