### ISSUE TITLE
npm install and run......doesn't work

### ISSUE THREAD

**Issue by ceballos59** [born2net/ng2Boilerplate#19]
Failed to load resource: the server responded with a status of 404 (Not Found)
system.js:4 Uncaught (in promise) Error: Error: XHR error (404 Not Found) loading http://localhost:9089/jspm_packages/github/twbs/bootstrap@3.3.6.json(…)

**Comment by Enlitened** [comment]
I'm also getting the same, everything appears to install correctly and the server starts up but when I navigate to the site in a browser I get that above error in the console.

**Comment by born2net** [comment]
fixed in version 0.6.0
