### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by willhartman** [born2net/ng2Boilerplate#2]
Seems to be a problem with reflect-metadata.  Any ideas?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose readDependencies loading dependencies from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\package.json
5 verbose install where, deps [ 'C:\\Users\\will.hartman\\Downloads\\ng2Boilerplate-master\\ng2Boilerplate-master',
5 verbose install   [ 'angular2',
5 verbose install     'bootstrap',
5 verbose install     'es6-module-loader',
5 verbose install     'es6-shim',
5 verbose install     'reflect-metadata',
5 verbose install     'rxjs',
5 verbose install     'systemjs',
5 verbose install     'zone.js',
5 verbose install     'browser-sync',
5 verbose install     'chalk',
5 verbose install     'crypto',
5 verbose install     'express',
5 verbose install     'gulp',
5 verbose install     'gulp-git',
5 verbose install     'gulp-inject',
5 verbose install     'gulp-typedoc',
5 verbose install     'gulp-typescript',
5 verbose install     'gulp-uglify',
5 verbose install     'gulp-util',
5 verbose install     'gulp-watch',
5 verbose install     'lodash',
5 verbose install     'ng2-file-upload',
5 verbose install     'rsync',
5 verbose install     'run-sequence',
5 verbose install     'tsd',
5 verbose install     'tslint',
5 verbose install     'typedoc',
5 verbose install     'typescript' ] ]
6 verbose install where, peers [ 'C:\\Users\\will.hartman\\Downloads\\ng2Boilerplate-master\\ng2Boilerplate-master',
6 verbose install   [] ]
7 verbose installManyTop reading for lifecycle C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\package.json
8 info preinstall ng2Boilerplater@0.4.2
9 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\angular2\package.json
10 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\bootstrap\package.json
11 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\browser-sync\package.json
12 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\chalk\package.json
13 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\crypto\package.json
14 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\es6-module-loader\package.json
15 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\es6-promise\package.json
16 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\es6-shim\package.json
17 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\express\package.json
18 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp\package.json
19 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-git\package.json
20 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-inject\package.json
21 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-typedoc\package.json
22 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-typescript\package.json
23 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-uglify\package.json
24 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-util\package.json
25 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-watch\package.json
26 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\lodash\package.json
27 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\ng2-file-upload\package.json
28 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\reflect-metadata\package.json
29 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\rsync\package.json
30 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\run-sequence\package.json
31 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\rxjs\package.json
32 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\systemjs\package.json
33 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\tsd\package.json
34 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\tslint\package.json
35 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\typedoc\package.json
36 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\typescript\package.json
37 verbose installManyTop reading scoped package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\zone.js\package.json
38 info package.json tsd@0.6.5 No license field.
39 info package.json crypto@0.0.3 crypto is also the name of a node core module.
40 info package.json crypto@0.0.3 No license field.
41 info package.json gulp-inject@1.5.0 No license field.
42 info package.json es6-module-loader@0.17.10 No license field.
43 info package.json gulp-typedoc@1.2.1 license should be a valid SPDX license expression
44 verbose readDependencies loading dependencies from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\package.json
45 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\angular2\package.json
46 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\bootstrap\package.json
47 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\browser-sync\package.json
48 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\chalk\package.json
49 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\crypto\package.json
50 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\es6-module-loader\package.json
51 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\es6-promise\package.json
52 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\es6-shim\package.json
53 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\express\package.json
54 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp\package.json
55 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-git\package.json
56 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-inject\package.json
57 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-typedoc\package.json
58 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-typescript\package.json
59 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-uglify\package.json
60 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-util\package.json
61 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\gulp-watch\package.json
62 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\lodash\package.json
63 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\ng2-file-upload\package.json
64 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\reflect-metadata\package.json
65 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\rsync\package.json
66 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\run-sequence\package.json
67 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\rxjs\package.json
68 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\systemjs\package.json
69 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\tsd\package.json
70 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\tslint\package.json
71 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\typedoc\package.json
72 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\typescript\package.json
73 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\zone.js\package.json
74 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\browser-sync\package.json
75 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\browser-sync.cmd\package.json
76 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\tsc\package.json
77 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\tsc.cmd\package.json
78 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\tsd\package.json
79 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\tsd.cmd\package.json
80 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\tslint\package.json
81 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\tslint.cmd\package.json
82 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\tsserver\package.json
83 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\tsserver.cmd\package.json
84 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\typedoc\package.json
85 verbose targetResolver reading package data from C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\.bin\typedoc.cmd\package.json
86 verbose already installed skipping rxjs@5.0.0-beta.0 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
87 verbose already installed skipping systemjs@^0.19.4 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
88 verbose already installed skipping zone.js@0.5.10 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
89 verbose already installed skipping browser-sync@~2.10.1 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
90 verbose already installed skipping chalk@^1.1.1 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
91 verbose already installed skipping crypto@0.0.3 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
92 verbose already installed skipping express@~4.13.1 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
93 verbose already installed skipping gulp@^3.9.0 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
94 verbose already installed skipping gulp-git@^1.6.0 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
95 verbose already installed skipping gulp-inject@^1.3.1 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
96 verbose already installed skipping gulp-typedoc@^1.2.1 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
97 verbose already installed skipping gulp-typescript@~2.8.2 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
98 verbose already installed skipping gulp-uglify@^1.2.0 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
99 verbose already installed skipping gulp-util@^3.0.7 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
100 verbose already installed skipping gulp-watch@^4.2.4 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
101 verbose already installed skipping lodash@^3.10.1 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
102 verbose already installed skipping ng2-file-upload@^0.46.0 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
103 verbose already installed skipping rsync@^0.4.0 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
104 verbose already installed skipping run-sequence@^1.1.5 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
105 verbose already installed skipping tsd@^0.6.5 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
106 verbose already installed skipping tslint@^3.2.1 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
107 verbose already installed skipping typedoc@^0.3.12 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
108 verbose already installed skipping typescript@~1.7.3 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
109 verbose already installed skipping angular2@2.0.0-beta.0 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
110 verbose already installed skipping bootstrap@^3.3.5 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
111 verbose already installed skipping es6-module-loader@^0.17.8 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
112 verbose already installed skipping es6-shim@^0.33.6 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
113 verbose already installed skipping reflect-metadata@^0.1.2 C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
114 silly install resolved []
115 info build C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
116 info linkStuff ng2Boilerplater@0.4.2
117 silly linkStuff ng2Boilerplater@0.4.2 has C:\Users\will.hartman\Downloads\ng2Boilerplate-master as its parent node_modules
118 verbose linkBins ng2Boilerplater@0.4.2
119 verbose linkMans ng2Boilerplater@0.4.2
120 verbose rebuildBundles ng2Boilerplater@0.4.2
121 verbose rebuildBundles [ '.bin',
121 verbose rebuildBundles   'angular2',
121 verbose rebuildBundles   'bootstrap',
121 verbose rebuildBundles   'browser-sync',
121 verbose rebuildBundles   'chalk',
121 verbose rebuildBundles   'crypto',
121 verbose rebuildBundles   'es6-module-loader',
121 verbose rebuildBundles   'es6-promise',
121 verbose rebuildBundles   'es6-shim',
121 verbose rebuildBundles   'express',
121 verbose rebuildBundles   'gulp',
121 verbose rebuildBundles   'gulp-git',
121 verbose rebuildBundles   'gulp-inject',
121 verbose rebuildBundles   'gulp-typedoc',
121 verbose rebuildBundles   'gulp-typescript',
121 verbose rebuildBundles   'gulp-uglify',
121 verbose rebuildBundles   'gulp-util',
121 verbose rebuildBundles   'gulp-watch',
121 verbose rebuildBundles   'lodash',
121 verbose rebuildBundles   'ng2-file-upload',
121 verbose rebuildBundles   'reflect-metadata',
121 verbose rebuildBundles   'rsync',
121 verbose rebuildBundles   'run-sequence',
121 verbose rebuildBundles   'rxjs',
121 verbose rebuildBundles   'systemjs',
121 verbose rebuildBundles   'tsd',
121 verbose rebuildBundles   'tslint',
121 verbose rebuildBundles   'typedoc',
121 verbose rebuildBundles   'typescript',
121 verbose rebuildBundles   'zone.js' ]
122 verbose rebuild bundle C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\es6-promise
123 info build C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules\es6-promise
124 info preinstall es6-promise@3.0.2
125 info linkStuff es6-promise@3.0.2
126 silly linkStuff es6-promise@3.0.2 has C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\node_modules as its parent node_modules
127 verbose linkBins es6-promise@3.0.2
128 verbose linkMans es6-promise@3.0.2
129 verbose rebuildBundles es6-promise@3.0.2
130 info install es6-promise@3.0.2
131 info postinstall es6-promise@3.0.2
132 info install ng2Boilerplater@0.4.2
133 info postinstall ng2Boilerplater@0.4.2
134 info prepublish ng2Boilerplater@0.4.2
135 verbose validateInstall loading C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master\package.json for validation
136 verbose stack Error: The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!
136 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:125:32
136 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:268:7
136 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
136 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
136 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
136 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
136 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
136 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
136 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
136 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
137 verbose cwd C:\Users\will.hartman\Downloads\ng2Boilerplate-master\ng2Boilerplate-master
138 error Windows_NT 6.3.9600
139 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
140 error node v4.2.4
141 error npm  v2.14.12
142 error code EPEERINVALID
143 error peerinvalid The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!
143 error peerinvalid Peer angular2@2.0.0-beta.0 wants reflect-metadata@0.1.2
144 verbose exit [ 1, true ]

**Comment by born2net** [comment]
try and install manually
npm install reflect-metadata

**Comment by willhartman** [comment]
Seems to be throwing a similar error -

175 error peerinvalid The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!
175 error peerinvalid Peer angular2@2.0.0-beta.0 wants reflect-metadata@0.1.2

**Comment by willhartman** [comment]
Tweaked the relevant line in package.json from -

    "reflect-metadata": "^0.1.2"

To -

    "reflect-metadata": "0.1.2"

And now working all OK.  Thanks for your help.  I can submit a PR if you like but nothing to it really.

**Comment by born2net** [comment]
will fix in code np tx!
