### ISSUE TITLE
angular 2 loading

### ISSUE THREAD

**Issue by foxjazz** [born2net/ng2Boilerplate#20]
After npm install it starts with Angular 2 loading

SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
http://localhost:8080/jspm_packages/github/twbs/bootstrap@3.3.6.json Failed to load resource: the server responded with a status of 404 (Not Found)
index.html:50 Error: Error: XHR error (404 Not Found) loading http://localhost:8080/jspm_packages/github/twbs/bootstrap@3.3.6.json(…) "error system.js Error: Error: XHR error (404 Not Found) loading http://localhost:8080/jspm_packages/github/twbs/bootstrap@3.3.6.json
	Error loading http://localhost:8080/jspm_packages/github/twbs/bootstrap@3.3.6.json
	Error loading http://localhost:8080/src/App.ts"

**Comment by born2net** [comment]
Are you sure you are and 6.6.0 as this was fixed today

**Comment by foxjazz** [comment]
After npm install this morning and the hotloader commands. I ran gulp development clicked on the link.



:hov


.cls

element.style {
}
user agent stylesheet
body {
    display: block;
    margin: 8px;
}
margin8
8border‒
‒padding‒
‒636 × 1203‒
‒‒
‒8
8

Console





Preserve log
﻿
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
system.src.js:5112 GET http://localhost:8080/jspm_packages/github/twbs/bootstrap@3.3.6.json 404 (Not Found)
index.html:50 Error: Error: XHR error (404 Not Found) loading http://localhost:8080/jspm_packages/github/twbs/bootstrap@3.3.6.json(…) "error system.js Error: Error: XHR error (404 Not Found) loading http://localhost:8080/jspm_packages/github/twbs/bootstrap@3.3.6.json
	Error loading http://localhost:8080/jspm_packages/github/twbs/bootstrap@3.3.6.json
	Error loading http://localhost:8080/src/App.ts"

**Comment by born2net** [comment]
I tried it and works for me...
as a workaround run:
```
jspm install github:twbs/bootstrap
```
let me know

**Comment by hellofornow** [comment]
twbs/bootstrap isn't in package.json
I needed to manually run jspm install as well
Great repo btw.

**Comment by born2net** [comment]
updated again but it should be under
```
"devDependencies": {
      "angular-platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@^2.0.0-rc.1",
      "bootstrap": "github:twbs/bootstrap@^3.3.6",
      ...
```
