### ISSUE TITLE
Failed to load resource... 404 Not found (Typescript issue?)

### ISSUE THREAD

**Issue by borntorun** [born2net/ng2Boilerplate#22]
When running with `npm run devserver` I get several errors "Failed to load resource..." for ts files.

The problem is with filename's case. For example, trying to load `src/comps/sidemenu/Menu.ts` but the file is in lowercase `.../menu.ts`.

Maybe a typescript issue? (I'm using 2.0.0-dev.20160628)

How to fix this? 
 
![virtualbox_centos_29_06_2016_00_29_59](https://cloud.githubusercontent.com/assets/820692/16436064/abb86628-3d92-11e6-858e-92ca906c520d.jpg)

**Comment by born2net** [comment]
it's odd as I fixed the case long time ago, try and rename all to lower case just to make sure its the issue...

**Comment by borntorun** [comment]
Yes, I tried that and that's the cause indeed.

**Comment by born2net** [comment]
ok will make a note to check asap

**Comment by born2net** [comment]
fixed!

**Comment by borntorun** [comment]
It's not only `.../Menu.ts` ... In the pic attached you can see the rest of the files with the same issue.

**Comment by born2net** [comment]
ha ok will check, which OS are you on?

**Comment by borntorun** [comment]
Linux (CentOS 7)

**Comment by borntorun** [comment]
How come you do not have this issue in your demo?

**Comment by NicholasGlazer** [comment]
Have similar issue.  OS: Arch Linux, npm: 3.9.6, node: 6.2.1.
<details> 
  <summary>After: `npm install`</summary>
    ![screenshot from 2016-06-29 15-49-45]   (https://cloud.githubusercontent.com/assets/7410355/16452515/9aa38032-3e11-11e6-979f-f623b2cae0ad.png)
</details>
<details> 
  <summary>After: `gulp development`</summary>

![screenshot from 2016-06-29 16-01-09](https://cloud.githubusercontent.com/assets/7410355/16452885/6cfb1454-3e13-11e6-8ced-db0934c78720.png)
</details>
<details> 
  <summary>After: `npm run devserver`</summary>
   ![screenshot from 2016-06-29 16-02-12](https://cloud.githubusercontent.com/assets/7410355/16452891/6f89439e-3e13-11e6-8185-030a9aafc2e7.png)
</details>

**Comment by ZuBB** [comment]
same thing. getting 404 for `Starwars.ts`, `Minitabs.ts` and `Minitab.ts`

**Comment by born2net** [comment]
did major refactoring today to jspm, please try again!
