### ISSUE TITLE
does not remember place when refreshing screen

### ISSUE THREAD

**Issue by arcee123** [born2net/ng2Boilerplate#26]
Greetings,

If I'm in a given page: e.g. http://localhost:8080/src/public/AppManager
the application works, but when the browser's refresh button is selected,
I receive the following error:

Cannot GET /src/public/AppManager

how do I enable this?
Thank you.

**Comment by born2net** [comment]
correct, this is a bug which will get fixed once I move to webpack.
I am waiting for ng2 team to finish cli @ webpack so I can make the move,
regards.
