### ISSUE TITLE
Usability question

### ISSUE THREAD

**Issue by bjornharvold** [born2net/ng2Boilerplate#29]
Hi,

This is more a gulp configuration question than anything else. Ideally, I'd like to run the app from the root domain and not from a sub-directory like src/public/index.html. I want to be able to go to localhost:8080 and have the gulp configuration use /src/public as doc root. This way I mimic a production environment closer.

Is that something that's easy to do with your setup?

Thank you

**Comment by born2net** [comment]
sure the entire production gulp script bundles into a single file, so you can host at any path you like, easy!

**Comment by bjornharvold** [comment]
I was referring to the development environment. This is not a big deal. Just asking if it's an easy configuration change.
