### ISSUE TITLE
jspm install systemjs-hot-reloader --dev

### ISSUE THREAD

**Issue by AndersMygind** [born2net/ng2Boilerplate#30]
Hello
I am trying to build this boilerplate.
When I 
jspm install systemjs-hot-reloader --dev
I get 
![image](https://cloud.githubusercontent.com/assets/5576607/18875109/a0747314-84c4-11e6-9d1d-25b9eba3c4b5.png)

**Comment by born2net** [comment]
please follow instructions
you need jspm beta 0.17
follow each and every command in readme

**Comment by AndersMygind** [comment]
thanks for answering.
Maybe i'm missing something.
npm install jspm@0.17.0-beta.28 - giving me the same result. Is it another beta 0.17?

**Comment by born2net** [comment]
wipe everything and do:

```
git clone https://github.com/born2net/ng2Boilerplate.git
cd ng2Boilerplate
npm install -g jspm@beta
npm install -g gulp
npm install
```

**Comment by AndersMygind** [comment]
working - when I used 
git clone https://github.com/born2net/ng2Boilerplate.git
it worked - that was the only thing I had not done.
Thought I could just download ... thanks
