### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by drejohnson** [born2net/ng2Boilerplate#5]
Why use Redux and not [ngrx/store](https://github.com/ngrx/store)?

**Comment by born2net** [comment]
after investigating I just really liked the eco system around Redux like the amazing new devtool  https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?utm_source=chrome-app-launcher-info-dialog   and Reselect middleware and more..

+ I know it's all short term as I am sure soon Google will have their own "Redux/Flux" Modeling for ng2 which we will all end up using anyways...

regards
