### ISSUE TITLE
Minitabs.ts is missing

### ISSUE THREAD

**Issue by rosshinkley** [born2net/ng2Boilerplate#9]
The [commit to include minitabs ](https://github.com/born2net/ng2Boilerplate/commit/b22e6208382aa5a256541d4148484b04cad6831a) is missing `Minitabs.ts`.  Can you check it in, please?

**Comment by born2net** [comment]
on it...!

**Comment by born2net** [comment]
try now

**Comment by rosshinkley** [comment]
Thank you. :)
